steps:
  release:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: "madnificent/${CI_REPO_NAME%%service}"
      tags: "${CI_COMMIT_TAG##v}"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
when:
  - event: tag
    ref: refs/tags/v*
